"""updated the exercice table and added  3 reference tables for the body part , the equipment and the muscle worked

Revision ID: 1fca7c3ad2e1
Revises: 82810cfd6755
Create Date: 2026-08-18 11:16:19.784414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fca7c3ad2e1'
down_revision: Union[str, Sequence[str], None] = '82810cfd6755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('equipment_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('exercise', sa.Column('body_part_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('exercise', sa.Column('target_muscle_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('exercise', sa.Column('synergist_muscle_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('exercise', 'equipment')
    op.drop_column('exercise', 'is_compound')
    op.drop_column('exercise', 'muscle_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('muscle_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('is_compound', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('equipment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercise', 'synergist_muscle_ids')
    op.drop_column('exercise', 'target_muscle_ids')
    op.drop_column('exercise', 'body_part_ids')
    op.drop_column('exercise', 'equipment_ids')
    op.drop_column('exercise', 'image_url')
    # ### end Alembic commands ###
