"""Added a user table and foreign key to the other tables 

Revision ID: 20efa1c35a28
Revises: 0e4b34f13101
Create Date: 2026-08-21 11:57:03.007979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20efa1c35a28'
down_revision: Union[str, Sequence[str], None] = '0e4b34f13101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE_HEALTH', 'FATSECRET', 'LYFTA', name='provider'), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_credentials_user_provider')
    )
    op.add_column('body_measurement', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_body_measurement_time_type'), 'body_measurement', type_='unique')
    op.create_unique_constraint('uq_body_measurement_user_time_type', 'body_measurement', ['user_id', 'measured_at', 'measure_type_id'])
    op.create_foreign_key(None, 'body_measurement', 'users', ['user_id'], ['id'])
    op.add_column('daily_health', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_daily_health_user_date', 'daily_health', ['user_id', 'date'])
    op.create_foreign_key(None, 'daily_health', 'users', ['user_id'], ['id'])
    op.add_column('daily_nutrition', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'daily_nutrition', 'users', ['user_id'], ['id'])
    op.add_column('daily_summary', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_daily_summary_user_date', 'daily_summary', ['user_id', 'date'])
    op.create_foreign_key(None, 'daily_summary', 'users', ['user_id'], ['id'])
    op.add_column('progress_photos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'progress_photos', 'users', ['user_id'], ['id'])
    op.add_column('sync_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_sync_history_user_date', 'sync_history', ['user_id', 'started_at'])
    op.create_foreign_key(None, 'sync_history', 'users', ['user_id'], ['id'])
    op.add_column('weekly_summary', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_weekly_summary_user_week_start', 'weekly_summary', ['user_id', 'week_start'])
    op.create_foreign_key(None, 'weekly_summary', 'users', ['user_id'], ['id'])
    op.add_column('workout_session', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_workout_session_started_at'), 'workout_session', type_='unique')
    op.create_unique_constraint('uq_workout_session_user_started_at', 'workout_session', ['user_id', 'started_at'])
    op.create_foreign_key(None, 'workout_session', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_session', type_='foreignkey')
    op.drop_constraint('uq_workout_session_user_started_at', 'workout_session', type_='unique')
    op.create_unique_constraint(op.f('uq_workout_session_started_at'), 'workout_session', ['started_at'], postgresql_nulls_not_distinct=False)
    op.drop_column('workout_session', 'user_id')
    op.drop_constraint(None, 'weekly_summary', type_='foreignkey')
    op.drop_constraint('uq_weekly_summary_user_week_start', 'weekly_summary', type_='unique')
    op.drop_column('weekly_summary', 'user_id')
    op.drop_constraint(None, 'sync_history', type_='foreignkey')
    op.drop_constraint('uq_sync_history_user_date', 'sync_history', type_='unique')
    op.drop_column('sync_history', 'user_id')
    op.drop_constraint(None, 'progress_photos', type_='foreignkey')
    op.drop_column('progress_photos', 'user_id')
    op.drop_constraint(None, 'daily_summary', type_='foreignkey')
    op.drop_constraint('uq_daily_summary_user_date', 'daily_summary', type_='unique')
    op.drop_column('daily_summary', 'user_id')
    op.drop_constraint(None, 'daily_nutrition', type_='foreignkey')
    op.drop_column('daily_nutrition', 'user_id')
    op.drop_constraint(None, 'daily_health', type_='foreignkey')
    op.drop_constraint('uq_daily_health_user_date', 'daily_health', type_='unique')
    op.drop_column('daily_health', 'user_id')
    op.drop_constraint(None, 'body_measurement', type_='foreignkey')
    op.drop_constraint('uq_body_measurement_user_time_type', 'body_measurement', type_='unique')
    op.create_unique_constraint(op.f('uq_body_measurement_time_type'), 'body_measurement', ['measured_at', 'measure_type_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('body_measurement', 'user_id')
    op.drop_table('user_credentials')
    op.drop_table('users')
    # ### end Alembic commands ###
