"""add unique constraints for idempotency

Revision ID: 82810cfd6755
Revises: 903e1260ce06
Create Date: 2026-08-14 12:10:58.252056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82810cfd6755'
down_revision: Union[str, Sequence[str], None] = '903e1260ce06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workout_pr_session_exercise_metric', 'workout_pr', ['session_id', 'exercise_id', 'metric'])
    op.create_unique_constraint('uq_workout_session_started_at', 'workout_session', ['started_at'])
    op.create_unique_constraint('uq_workout_set_session_exercise_number', 'workout_set', ['session_id', 'exercise_id', 'set_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workout_set_session_exercise_number', 'workout_set', type_='unique')
    op.drop_constraint('uq_workout_session_started_at', 'workout_session', type_='unique')
    op.drop_constraint('uq_workout_pr_session_exercise_metric', 'workout_pr', type_='unique')
    # ### end Alembic commands ###
