"""initial schema

Revision ID: 8c87dfade077
Revises: 
Create Date: 2026-08-06 20:26:01.211925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c87dfade077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Numeric(), nullable=True),
    sa.Column('calories_burned', sa.Numeric(), nullable=True),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('daily_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Numeric(), nullable=True),
    sa.Column('protein', sa.Numeric(), nullable=True),
    sa.Column('fat', sa.Numeric(), nullable=True),
    sa.Column('carbs', sa.Numeric(), nullable=True),
    sa.Column('fiber', sa.Numeric(), nullable=True),
    sa.Column('water', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('health_score', sa.Numeric(), nullable=True),
    sa.Column('training_load', sa.Numeric(), nullable=True),
    sa.Column('calorie_balance', sa.Numeric(), nullable=True),
    sa.Column('weekly_volume', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('is_compound', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measure_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Enum('COMPOSITION', 'TAPE_MEASUREMENT', name='measurecategory'), nullable=False),
    sa.Column('unit_default', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view', sa.Enum('FRONT', 'SIDE', 'BACK', name='photoview'), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'RUNNING', name='syncstatus'), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.Enum('SCHEDULED', 'MANUAL', name='triggertype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='summarystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start')
    )
    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('sources', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('measure_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measure_type_id'], ['measure_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measured_at', 'measure_type_id', name='uq_body_measurement_time_type')
    )
    op.create_table('workout_pr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('is_warmup', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=False),
    sa.Column('rpe', sa.Numeric(), nullable=True),
    sa.Column('rir', sa.Numeric(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_set')
    op.drop_table('workout_pr')
    op.drop_table('body_measurement')
    op.drop_table('workout_session')
    op.drop_table('weekly_summary')
    op.drop_table('sync_history')
    op.drop_table('progress_photos')
    op.drop_table('measure_type')
    op.drop_table('exercise')
    op.drop_table('daily_summary')
    op.drop_table('daily_nutrition')
    op.drop_table('daily_health')
    # ### end Alembic commands ###
