"""add reps to workout_set

Revision ID: 903e1260ce06
Revises: 8c87dfade077
Create Date: 2026-08-13 10:27:11.280959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903e1260ce06'
down_revision: Union[str, Sequence[str], None] = '8c87dfade077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_set', sa.Column('reps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_set', 'reps')
    # ### end Alembic commands ###
