name: Plan terraform config
description: Plan using terraform latest configuration

inputs:
  github_role_arn:
    description: ARN of the role to assume in order to apply terraform configuration
    required: true

runs:
  using: composite
  steps:
    - name: Debug GitHub context
      shell: bash
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Ref: $GITHUB_REF"
        echo "Workflow: $GITHUB_WORKFLOW"
        echo "Event: $GITHUB_EVENT_NAME"

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.github_role_arn }}
        aws-region: eu-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.11"
    - name: Terraform init
      working-directory: terraform/main
      shell: bash
      run: terraform init
    
    - name: Download dispatcher artifact
      uses: actions/download-artifact@v4
      with:
        name: dispatcher-lambda
        path: terraform/main

    - name: Terraform Plan
      working-directory: terraform/main
      shell: bash
      run: terraform plan -out=tfplan

    - name: Upload plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: infra/tfplan
        retention-days: 1